import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { FaCode } from "react-icons/fa";
import Image from "next/image";
import joona from "../public/joona.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Joona Luukkonen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-200">
              <FaCode className="text-2xl dark:text-gray-200" />
            </h1>
            <ul className="flex items-start">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-gray-200"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to to-teal-500 text-white px-4 py-2 rounded-md ml-8
                "
                  href="https://www.canva.com/design/DAFTb2qnQsQ/xMK_7n1zgk1t5tap1v0zmA/view?utm_content=DAFTb2qnQsQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
                >
                  Ansioluettelo
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 dark:text-gray-200">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Joona Luukkonen
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Web Developer</h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              Olen Joona, 26-vuotias IT-Tradenomi opiskelija Vaasasta. Olen
              utelias koodaaja, joka tykkää pujahtaa Googlen syövereihin. Näen
              ohjelmoinnin palapelinä, jota lähden kokoamaan pala kerrallaan.
              Palasien etsiminen voi välillä viedä aikaa, mutta kun ne oikeat
              palat löytää niin se palkitsee ja motivoi menemään projektissa
              eteenpäin.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-black dark:text-teal-600">
            <AiFillGithub />
            <AiFillLinkedin />
          </div>
          <div>
            <Image
              src={joona}
              alt="joona"
              className="rounded-full object-cover mx-auto w-80 h-80 mt-20 md:h-96 md:w-96"
            />
          </div>
        </section>
        <section>
          <div className="mt-20">
            <h3 className="text-3xl py-1 text-teal-600 font-medium ">
              Portfolio / Harrasteprojektit
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Toteutan projektini pääsääntöisesti Reactilla ja Node.js:llä.
              Reactin parissa olen duunaillut noin vuoden verran. Myös Reactiin
              kuuluvia frameworkkejä on tullut testailtua mm. Next.js ja
              Gatsby.js.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit
              delectus similique porro ut possimus, reiciendis corrupti
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 ">
              <Image
                src={design}
                alt="design"
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Beautiful designs
              </h3>
              <p className="py-4 dark:text-gray-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam
                ex porro ea libero repellendus possimus perspiciatis
                consequuntur
              </p>
              <h4 className="py-4 text-teal-600">design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">ipsum</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">dolor</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 ">
              <Image
                src={code}
                alt="code"
                width={100}
                height={100}
                className="mx-auto"
              />

              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Beautiful designs
              </h3>
              <p className="py-4 dark:text-gray-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam
                ex porro ea libero repellendus possimus perspiciatis
                consequuntur
              </p>
              <h4 className="py-4 text-teal-600">design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">ipsum</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">dolor</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-800">
              <Image
                src={consulting}
                alt="consulting"
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Beautiful designs
              </h3>
              <p className="py-4 dark:text-gray-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam
                ex porro ea libero repellendus possimus perspiciatis
                consequuntur
              </p>
              <h4 className="py-4 text-teal-600">design tools i use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">ipsum</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">dolor</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Lorem</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
